name: CI/CD for Tempo Log Assistant

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install UV
      run: pip install uv

    - name: Install dependencies
      run: pip install pytest

    - name: Sync dependencies
      run: uv sync

    - name: Run tests
      run: uv run pytest
